# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160224_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='country',
            field=models.CharField(choices=[('US', 'United States')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='address_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
