# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20160224_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
