# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 06:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_registeruser_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 24, 6, 59, 27, 148154)),
            preserve_default=False,
        ),
    ]
