# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20160224_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='postal',
            field=models.IntegerField(max_length=9, validators=[users.validators.validate_five_or_nine]),
        ),
    ]
